/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetalpipeIndexRouteImport } from './routes/metalpipe/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as MetalpipeDownloadRouteImport } from './routes/metalpipe/download'
import { Route as BlogPostIdRouteImport } from './routes/blog/$postId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetalpipeIndexRoute = MetalpipeIndexRouteImport.update({
  id: '/metalpipe/',
  path: '/metalpipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const MetalpipeDownloadRoute = MetalpipeDownloadRouteImport.update({
  id: '/metalpipe/download',
  path: '/metalpipe/download',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BlogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/metalpipe/download': typeof MetalpipeDownloadRoute
  '/blog/': typeof BlogIndexRoute
  '/metalpipe': typeof MetalpipeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/metalpipe/download': typeof MetalpipeDownloadRoute
  '/blog': typeof BlogIndexRoute
  '/metalpipe': typeof MetalpipeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/metalpipe/download': typeof MetalpipeDownloadRoute
  '/blog/': typeof BlogIndexRoute
  '/metalpipe/': typeof MetalpipeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/$'
    | '/blog/$postId'
    | '/metalpipe/download'
    | '/blog/'
    | '/metalpipe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/blog/$postId'
    | '/metalpipe/download'
    | '/blog'
    | '/metalpipe'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/$'
    | '/blog/$postId'
    | '/metalpipe/download'
    | '/blog/'
    | '/metalpipe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  MetalpipeDownloadRoute: typeof MetalpipeDownloadRoute
  MetalpipeIndexRoute: typeof MetalpipeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metalpipe/': {
      id: '/metalpipe/'
      path: '/metalpipe'
      fullPath: '/metalpipe'
      preLoaderRoute: typeof MetalpipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/metalpipe/download': {
      id: '/metalpipe/download'
      path: '/metalpipe/download'
      fullPath: '/metalpipe/download'
      preLoaderRoute: typeof MetalpipeDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof BlogRouteRoute
    }
  }
}

interface BlogRouteRouteChildren {
  BlogPostIdRoute: typeof BlogPostIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogPostIdRoute: BlogPostIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  MetalpipeDownloadRoute: MetalpipeDownloadRoute,
  MetalpipeIndexRoute: MetalpipeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
