/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetalPipeIndexRouteImport } from './routes/metal-pipe/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as MetalPipeAppRouteImport } from './routes/metal-pipe/app'
import { Route as BlogPostIdRouteImport } from './routes/blog/$postId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetalPipeIndexRoute = MetalPipeIndexRouteImport.update({
  id: '/metal-pipe/',
  path: '/metal-pipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const MetalPipeAppRoute = MetalPipeAppRouteImport.update({
  id: '/metal-pipe/app',
  path: '/metal-pipe/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BlogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/metal-pipe/app': typeof MetalPipeAppRoute
  '/blog/': typeof BlogIndexRoute
  '/metal-pipe': typeof MetalPipeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/metal-pipe/app': typeof MetalPipeAppRoute
  '/blog': typeof BlogIndexRoute
  '/metal-pipe': typeof MetalPipeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/metal-pipe/app': typeof MetalPipeAppRoute
  '/blog/': typeof BlogIndexRoute
  '/metal-pipe/': typeof MetalPipeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/$'
    | '/blog/$postId'
    | '/metal-pipe/app'
    | '/blog/'
    | '/metal-pipe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/blog/$postId' | '/metal-pipe/app' | '/blog' | '/metal-pipe'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/$'
    | '/blog/$postId'
    | '/metal-pipe/app'
    | '/blog/'
    | '/metal-pipe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  MetalPipeAppRoute: typeof MetalPipeAppRoute
  MetalPipeIndexRoute: typeof MetalPipeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metal-pipe/': {
      id: '/metal-pipe/'
      path: '/metal-pipe'
      fullPath: '/metal-pipe'
      preLoaderRoute: typeof MetalPipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/metal-pipe/app': {
      id: '/metal-pipe/app'
      path: '/metal-pipe/app'
      fullPath: '/metal-pipe/app'
      preLoaderRoute: typeof MetalPipeAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof BlogRouteRoute
    }
  }
}

interface BlogRouteRouteChildren {
  BlogPostIdRoute: typeof BlogPostIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogPostIdRoute: BlogPostIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  MetalPipeAppRoute: MetalPipeAppRoute,
  MetalPipeIndexRoute: MetalPipeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
